import AddOutlined from '@mui/icons-material/AddOutlined'
import ArchiveOutlined from '@mui/icons-material/ArchiveOutlined'
import EditOutlined from '@mui/icons-material/EditOutlined'
import OpenInNewOutlined from '@mui/icons-material/OpenInNewOutlined'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Grid, LinearProgress, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { careerApi } from '../api/client'
import { Feedback } from '../components/Feedback'
import { PageHeader } from '../components/PageHeader'
import type { Opportunity, OpportunityInput, Organisation } from '../types/career'

const types = ['Job', 'Award', 'Fellowship', 'Grant', 'Board / advisory', 'Government', 'Industry', 'Leadership', 'Thought leadership', 'Media', 'Custom']
const statuses = ['discovered', 'reviewing', 'planned', 'pursuing', 'submitted', 'won', 'lost', 'declined', 'expired']
const empty: OpportunityInput = { title: '', description: '', opportunity_type: 'Job', organisation_id: null, url: '', opening_date: null, closing_date: null, status: 'discovered', owner: '', next_action: '', notes: '', source: 'user', strategic_value: 3, probability: 50, effort: 3, score_input_source: 'user' }

function inputFor(item: Opportunity): OpportunityInput { return { title: item.title, description: item.description, opportunity_type: item.opportunity_type, organisation_id: item.organisation_id, url: item.url, opening_date: item.opening_date, closing_date: item.closing_date, status: item.status, owner: item.owner, next_action: item.next_action, notes: item.notes, source: item.source, strategic_value: item.assessment.strategic_value, probability: item.assessment.probability, effort: item.assessment.effort, score_input_source: item.assessment.input_source } }
function urgencyColor(level: string): 'error' | 'warning' | 'info' | 'default' { return level === 'critical' || level === 'overdue' ? 'error' : level === 'high' || level === 'medium' ? 'warning' : level === 'low' ? 'info' : 'default' }

function Editor({ open, item, organisations, onClose, onSaved }: { open: boolean; item: Opportunity | null; organisations: Organisation[]; onClose: () => void; onSaved: (item: Opportunity) => void }) {
  const [form, setForm] = useState<OpportunityInput>(empty); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (open) { setForm(item ? inputFor(item) : empty); setError(null) } }, [item, open])
  const set = <K extends keyof OpportunityInput>(key: K, value: OpportunityInput[K]) => setForm(current => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { onSaved(item ? await careerApi.updateOpportunity(item.id, form) : await careerApi.createOpportunity(form)); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save opportunity') } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><Box component="form" onSubmit={event => void submit(event)}><DialogTitle>{item ? 'Edit opportunity' : 'Add opportunity'}</DialogTitle><DialogContent><Alert severity="info" sx={{ mb: 2 }}>Use public professional information only. Scores are transparent and user inputs are never overwritten by AI.</Alert>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Grid container spacing={2}>
    <Grid size={12}><TextField required autoFocus fullWidth label="Title" value={form.title} onChange={e => set('title', e.target.value)} /></Grid>
    <Grid size={{ xs: 12, md: 6 }}><TextField select fullWidth label="Type" value={form.opportunity_type} onChange={e => set('opportunity_type', e.target.value)}>{types.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Grid>
    <Grid size={{ xs: 12, md: 6 }}><TextField select fullWidth label="Status" value={form.status} onChange={e => set('status', e.target.value)}>{statuses.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Grid>
    <Grid size={{ xs: 12, md: 6 }}><TextField select fullWidth label="Organisation" value={form.organisation_id ?? ''} onChange={e => set('organisation_id', e.target.value || null)}><MenuItem value="">None</MenuItem>{organisations.map(org => <MenuItem key={org.id} value={org.id}>{org.name}</MenuItem>)}</TextField></Grid>
    <Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Public URL" value={form.url} onChange={e => set('url', e.target.value)} /></Grid>
    <Grid size={{ xs: 12, md: 6 }}><TextField type="date" fullWidth label="Opening date" slotProps={{ inputLabel: { shrink: true } }} value={form.opening_date ?? ''} onChange={e => set('opening_date', e.target.value || null)} /></Grid>
    <Grid size={{ xs: 12, md: 6 }}><TextField type="date" fullWidth label="Closing date" slotProps={{ inputLabel: { shrink: true } }} value={form.closing_date ?? ''} onChange={e => set('closing_date', e.target.value || null)} /></Grid>
    <Grid size={12}><TextField fullWidth multiline minRows={2} label="Description" value={form.description} onChange={e => set('description', e.target.value)} /></Grid>
    <Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Owner" value={form.owner} onChange={e => set('owner', e.target.value)} /></Grid><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Next action" value={form.next_action} onChange={e => set('next_action', e.target.value)} /></Grid>
    <Grid size={12}><Typography fontWeight={800}>Priority assessment</Typography><Typography variant="body2" color="text.secondary">Score = (strategic value × probability) ÷ effort, normalized to 100. Urgency is separate.</Typography></Grid>
    <Grid size={{ xs: 12, md: 4 }}><TextField required type="number" fullWidth label="Strategic value (1–5)" value={form.strategic_value} slotProps={{ htmlInput: { min: 1, max: 5 } }} onChange={e => set('strategic_value', Number(e.target.value))} /></Grid>
    <Grid size={{ xs: 12, md: 4 }}><TextField required type="number" fullWidth label="Probability (0–100%)" value={form.probability} slotProps={{ htmlInput: { min: 0, max: 100 } }} onChange={e => set('probability', Number(e.target.value))} /></Grid>
    <Grid size={{ xs: 12, md: 4 }}><TextField required type="number" fullWidth label="Effort (1–5)" value={form.effort} slotProps={{ htmlInput: { min: 1, max: 5 } }} onChange={e => set('effort', Number(e.target.value))} /></Grid>
    <Grid size={12}><TextField fullWidth multiline minRows={2} label="Notes" value={form.notes} onChange={e => set('notes', e.target.value)} /></Grid>
  </Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save opportunity'}</Button></DialogActions></Box></Dialog>
}

export function OpportunitiesPage() {
  const [items, setItems] = useState<Opportunity[] | null>(null); const [organisations, setOrganisations] = useState<Organisation[]>([]); const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState(''); const [editing, setEditing] = useState<Opportunity | null>(null); const [open, setOpen] = useState(false); const [feedback, setFeedback] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { const params = new URLSearchParams(); if (search) params.set('search', search); if (type) params.set('opportunity_type', type); if (status) params.set('opportunity_status', status); try { setItems((await careerApi.listOpportunities(params)).items); setError(null) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load opportunities') } }, [search, status, type])
  useEffect(() => { void load() }, [load]); useEffect(() => { void careerApi.listOrganisations().then(setOrganisations) }, [])
  async function archive(item: Opportunity) { await careerApi.archiveOpportunity(item.id); setFeedback('Opportunity archived.'); void load() }
  return <><PageHeader eyebrow="OPPORTUNITY PRIORITISATION" title="Opportunities" description="Compare career opportunities with transparent, reproducible scoring while tracking deadlines and next actions separately." action={{ label: 'Add opportunity', icon: <AddOutlined />, onClick: () => { setEditing(null); setOpen(true) } }} />
    <Card sx={{ mb: 3 }}><CardContent><Grid container spacing={2}><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Search opportunities" value={search} onChange={e => setSearch(e.target.value)} /></Grid><Grid size={{ xs: 12, md: 3 }}><TextField select fullWidth label="Type" value={type} onChange={e => setType(e.target.value)}><MenuItem value="">All types</MenuItem>{types.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Grid><Grid size={{ xs: 12, md: 3 }}><TextField select fullWidth label="Status" value={status} onChange={e => setStatus(e.target.value)}><MenuItem value="">All statuses</MenuItem>{statuses.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Grid></Grid></CardContent></Card>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{!items ? <CircularProgress aria-label="Loading opportunities" /> : <Stack spacing={2}>{items.map((item, index) => <Card key={item.id}><CardContent><Grid container spacing={2} alignItems="center"><Grid size={{ xs: 12, md: 1 }}><Typography variant="h4" color="text.secondary">#{index + 1}</Typography></Grid><Grid size={{ xs: 12, md: 7 }}><Stack direction="row" gap={1} flexWrap="wrap"><Chip size="small" label={item.opportunity_type} color="primary" variant="outlined" /><Chip size="small" label={item.status} /><Chip size="small" label={item.urgency.label} color={urgencyColor(item.urgency.level)} /></Stack><Typography variant="h6" mt={1}>{item.title}</Typography><Typography color="text.secondary">{item.organisation_name || item.description || 'No organisation or description provided.'}</Typography><Typography mt={1}><strong>Next:</strong> {item.next_action || 'Define the next action'}</Typography></Grid><Grid size={{ xs: 12, md: 4 }}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>Priority score</Typography><Typography variant="h5" color="primary.main">{item.assessment.normalized_score}/100</Typography></Stack><LinearProgress variant="determinate" value={Math.min(item.assessment.normalized_score, 100)} sx={{ my: 1, height: 8, borderRadius: 2 }} /><Typography variant="caption" color="text.secondary">{item.assessment.explanation} Inputs: {item.assessment.input_source}; {item.assessment.algorithm_version}.</Typography><Stack direction="row" mt={1}><Button size="small" startIcon={<EditOutlined />} onClick={() => { setEditing(item); setOpen(true) }}>Edit</Button>{item.url && <Button size="small" href={item.url} target="_blank" startIcon={<OpenInNewOutlined />}>Source</Button>}<Button size="small" color="warning" startIcon={<ArchiveOutlined />} onClick={() => void archive(item)}>Archive</Button></Stack></Grid></Grid></CardContent></Card>)}</Stack>}
    {items?.length === 0 && <Alert severity="info">No opportunities match these filters. Add your first opportunity to begin prioritising.</Alert>}<Editor open={open} item={editing} organisations={organisations} onClose={() => setOpen(false)} onSaved={() => { setFeedback(editing ? 'Opportunity updated and reassessed.' : 'Opportunity created.'); void load() }} /><Feedback message={feedback} onClose={() => setFeedback(null)} /></>
}
