import AddOutlined from '@mui/icons-material/AddOutlined'
import AutoAwesomeOutlined from '@mui/icons-material/AutoAwesomeOutlined'
import ExpandMoreOutlined from '@mui/icons-material/ExpandMoreOutlined'
import { Accordion, AccordionDetails, AccordionSummary, Alert, Autocomplete, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Grid, LinearProgress, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { careerApi } from '../api/client'
import { Feedback } from '../components/Feedback'
import { PageHeader } from '../components/PageHeader'
import type { CareerAsset, CriterionAssessmentInput, CriterionInput, GoalReadiness, Target, TargetInput, TargetSuggestion } from '../types/career'

const emptyCriterion = (): CriterionInput => ({ title: '', description: '', weight: 1, sort_order: 0, provenance: 'user' })
const emptyTarget = (): TargetInput => ({ title: '', description: '', target_type: 'Role', status: 'adopted', target_date: null, provenance: 'user', criteria: [emptyCriterion()] })

function TargetEditor({ open, suggestion, onClose, onSaved }: { open: boolean; suggestion: TargetSuggestion | null; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<TargetInput>(emptyTarget()); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!open) return; setError(null); setForm(suggestion ? { title: suggestion.title, description: `${suggestion.description}\n\nRationale: ${suggestion.rationale}${suggestion.milestones.length ? `\n\nMilestones:\n${suggestion.milestones.map(x => `• ${x}`).join('\n')}` : ''}`, target_type: suggestion.target_type, status: 'adopted', target_date: null, provenance: 'ai', criteria: suggestion.criteria.map((item, index) => ({ ...item, sort_order: index, provenance: 'ai' })) } : emptyTarget()) }, [open, suggestion])
  const setCriterion = (index: number, changes: Partial<CriterionInput>) => setForm(current => ({ ...current, criteria: current.criteria.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item) }))
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await careerApi.createTarget(form); onSaved(); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save target') } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><Box component="form" onSubmit={event => void submit(event)}><DialogTitle>{suggestion ? 'Review and adopt suggested trajectory' : 'Create target'}</DialogTitle><DialogContent><Alert severity="info" sx={{ mb: 2 }}>Targets and criteria become authoritative only when you save them. AI suggestions can be edited before adoption.</Alert>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Grid container spacing={2}>
    <Grid size={{ xs: 12, md: 8 }}><TextField required fullWidth label="Target or trajectory" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField select fullWidth label="Type" value={form.target_type} onChange={e => setForm({ ...form, target_type: e.target.value })}>{['Role', 'Leadership', 'Recognition', 'Award', 'Fellowship', 'Advisory', 'Trajectory', 'Custom'].map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Grid>
    <Grid size={12}><TextField fullWidth multiline minRows={3} label="Description and desired trajectory" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField type="date" fullWidth label="Target date" slotProps={{ inputLabel: { shrink: true } }} value={form.target_date ?? ''} onChange={e => setForm({ ...form, target_date: e.target.value || null })} /></Grid>
    <Grid size={12}><Typography variant="h6">Weighted criteria</Typography></Grid>{form.criteria.map((criterion, index) => <Grid size={12} key={index}><Card variant="outlined"><CardContent><Grid container spacing={1.5}><Grid size={{ xs: 12, md: 8 }}><TextField required fullWidth label={`Criterion ${index + 1}`} value={criterion.title} onChange={e => setCriterion(index, { title: e.target.value })} /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField required type="number" fullWidth label="Weight" value={criterion.weight} slotProps={{ htmlInput: { min: 0.1, max: 100, step: 0.1 } }} onChange={e => setCriterion(index, { weight: Number(e.target.value) })} /></Grid><Grid size={12}><TextField fullWidth label="What satisfies this criterion?" value={criterion.description} onChange={e => setCriterion(index, { description: e.target.value })} /></Grid></Grid>{form.criteria.length > 1 && <Button color="warning" onClick={() => setForm(current => ({ ...current, criteria: current.criteria.filter((_, itemIndex) => itemIndex !== index) }))}>Remove criterion</Button>}</CardContent></Card></Grid>)}<Grid size={12}><Button onClick={() => setForm(current => ({ ...current, criteria: [...current.criteria, { ...emptyCriterion(), sort_order: current.criteria.length }] }))}>Add criterion</Button></Grid>
  </Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={busy}>{busy ? 'Saving…' : 'Adopt target'}</Button></DialogActions></Box></Dialog>
}

export function TargetsPage() {
  const [targets, setTargets] = useState<Target[] | null>(null); const [assets, setAssets] = useState<CareerAsset[]>([]); const [goalProgress, setGoalProgress] = useState<GoalReadiness[]>([]); const [assessments, setAssessments] = useState<Record<string, CriterionAssessmentInput>>({}); const [suggestions, setSuggestions] = useState<TargetSuggestion[]>([]); const [editor, setEditor] = useState(false); const [adopting, setAdopting] = useState<TargetSuggestion | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [feedback, setFeedback] = useState<string | null>(null)
  const load = useCallback(async () => { try { const [targetRows, assetRows, progressRows] = await Promise.all([careerApi.listTargets(), careerApi.listAssets(new URLSearchParams()), careerApi.goalReadiness()]); setTargets(targetRows); setAssets(assetRows.items); setGoalProgress(progressRows); setAssessments(current => { const next = { ...current }; for (const target of targetRows) for (const criterion of target.criteria) if (!next[criterion.id]) { const prior = target.latest_assessment?.criteria.find(item => item.criterion_id === criterion.id); next[criterion.id] = prior ? { criterion_id: criterion.id, coverage: prior.coverage, confidence: prior.confidence, explanation: prior.explanation, recommended_action: prior.recommended_action } : { criterion_id: criterion.id, coverage: criterion.asset_ids.length ? 60 : 0, confidence: criterion.evidence_ids.length ? 70 : 30, explanation: criterion.asset_ids.length ? 'Mapped career assets provide partial or complete support.' : 'No supporting career assets are mapped.', recommended_action: criterion.asset_ids.length ? 'Validate the mapped evidence and close any remaining gap.' : 'Build or identify evidence for this criterion.' } } return next }); setError(null) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load targets') } }, [])
  useEffect(() => { void load() }, [load])
  async function mapAssets(criterionId: string, selected: CareerAsset[]) { const evidenceIds = selected.flatMap(asset => asset.evidence.map(item => item.id)); await careerApi.mapCriterion(criterionId, selected.map(item => item.id), [...new Set(evidenceIds)]); setFeedback('Evidence mapping updated. Reassess to create a new readiness version.'); void load() }
  async function assessGoal(goalId: string) { setBusy(true); setError(null); try { const result = await careerApi.autoAssessGoal(goalId); setFeedback(`Existing achievements mapped to goal. Readiness ${result.readiness_score}%.`); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to assess strategic goal') } finally { setBusy(false) } }
  async function assess(target: Target) { setBusy(true); try { await careerApi.assessTarget(target.id, target.criteria.map(item => assessments[item.id])); setFeedback('Readiness assessment created as a new version.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to assess readiness') } finally { setBusy(false) } }
  async function autoMap(target: Target) { setBusy(true); setError(null); try { const result = await careerApi.autoMapTarget(target.id); setFeedback(`Existing career evidence mapped. Readiness v${result.version} created.`); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to map existing evidence') } finally { setBusy(false) } }
  async function suggest() { setBusy(true); setError(null); try { setSuggestions((await careerApi.suggestTargets()).suggestions) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to suggest trajectories') } finally { setBusy(false) } }
  return <><PageHeader eyebrow="TARGETS & READINESS" title="Career targets" description="Define the trajectory, weight what matters, map career evidence and track readiness without turning confidence into a success probability." action={{ label: 'Create target', icon: <AddOutlined />, onClick: () => { setAdopting(null); setEditor(true) } }} />
    <Stack direction="row" mb={3}><Button variant="outlined" startIcon={<AutoAwesomeOutlined />} onClick={() => void suggest()} disabled={busy}>{busy ? 'Working…' : 'Suggest trajectories with AI'}</Button></Stack>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Typography variant="h5" mb={1}>Strategic goal trajectory</Typography><Typography color="text.secondary" mb={2}>Every strategic goal uses the same readiness card and 0-100 scale. The evidence-basis label identifies whether the latest score came from a direct goal assessment or linked career-target assessments.</Typography>
    {goalProgress.length > 0 ? <Grid container spacing={2} mb={3}>{goalProgress.map(goal => <Grid key={goal.goal_id} size={{ xs: 12, md: 6, lg: 4 }}><Card sx={{ height: '100%' }}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography variant="overline">{goal.horizon.replaceAll('_', ' ')}</Typography><Typography variant="h6">{goal.title}</Typography></Box><Chip size="small" label={goal.status.replaceAll('_', ' ')} color={goal.status === 'on_track' ? 'success' : goal.status === 'needs_attention' ? 'warning' : 'default'} /></Stack><Chip sx={{ mt: 1 }} size="small" variant="outlined" label={goal.assessment_basis === 'direct_goal_evidence' ? 'Evidence basis: career achievements' : 'Evidence basis: linked targets'} /><Stack direction="row" justifyContent="space-between" alignItems="baseline" mt={2}><Typography variant="h4" color="primary.main">{goal.readiness_score === null ? '—' : `${goal.readiness_score}%`}</Typography>{goal.trend !== null && <Chip size="small" color={goal.trend >= 0 ? 'success' : 'warning'} label={`${goal.trend >= 0 ? '+' : ''}${goal.trend} since last assessment`} />}</Stack>{goal.readiness_score !== null && <LinearProgress variant="determinate" value={goal.readiness_score} sx={{ mt: 1, height: 8, borderRadius: 2 }} />}<Typography variant="body2" color="text.secondary" mt={2}>{goal.mapped_asset_titles.length ? `Mapped achievements: ${goal.mapped_asset_titles.slice(0, 3).join(' · ')}${goal.mapped_asset_titles.length > 3 ? ` +${goal.mapped_asset_titles.length - 3} more` : ''}` : goal.linked_target_titles.length ? `Linked targets: ${goal.linked_target_titles.join(' · ')}` : 'No evidence assessment has been saved yet.'}</Typography>{goal.explanation && <Typography variant="body2" mt={1}>{goal.explanation}</Typography>}<Typography variant="caption" display="block" mt={1}>{goal.trajectory.length} assessment version{goal.trajectory.length === 1 ? '' : 's'}{goal.target_date ? ` · target ${goal.target_date}` : ''}</Typography><Button fullWidth variant={goal.readiness_score === null ? 'contained' : 'outlined'} sx={{ mt: 2 }} disabled={busy} onClick={() => void assessGoal(goal.goal_id)}>{busy ? 'Assessing…' : goal.readiness_score === null ? 'Assess existing achievements with AI' : 'Reassess with current achievements'}</Button></CardContent></Card></Grid>)}</Grid> : <Alert severity="info" sx={{ mb: 3 }}>Add strategic goals in Profile & goals to begin goal-level progress tracking.</Alert>}
    {suggestions.length > 0 && <Card sx={{ mb: 3 }}><CardContent><Typography variant="h6">Unadopted AI suggestions</Typography><Typography color="text.secondary" mb={2}>These do not affect goals or readiness until you review and adopt one.</Typography><Stack spacing={1}>{suggestions.map((item, index) => <Card variant="outlined" key={index}><CardContent><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary">{item.rationale}</Typography><Button onClick={() => { setAdopting(item); setEditor(true) }}>Review and adopt</Button></CardContent></Card>)}</Stack></CardContent></Card>}
    {!targets ? <CircularProgress aria-label="Loading targets" /> : <Stack spacing={2}>{targets.map((target, index) => <Accordion key={target.id} defaultExpanded={index === 0}><AccordionSummary expandIcon={<ExpandMoreOutlined />}><Grid container spacing={2} alignItems="center" width="100%"><Grid size={{ xs: 12, md: 8 }}><Stack direction="row" gap={1} flexWrap="wrap" mb={0.75}><Chip size="small" label={target.target_type} color="primary" variant="outlined" /><Chip size="small" label={target.status} /></Stack><Typography variant="h6">{target.title}</Typography></Grid><Grid size={{ xs: 12, md: 4 }}><Stack direction="row" justifyContent="space-between"><Typography variant="body2" color="text.secondary">{target.latest_assessment ? `Readiness v${target.latest_assessment.version}` : 'Not assessed'}</Typography><Typography variant="h6" color="primary.main">{target.latest_assessment ? `${target.latest_assessment.readiness_score}%` : '—'}</Typography></Stack>{target.latest_assessment && <LinearProgress variant="determinate" value={target.latest_assessment.readiness_score} sx={{ mt: 0.75, height: 7, borderRadius: 2 }} />}</Grid></Grid></AccordionSummary><AccordionDetails sx={{ borderTop: '1px solid', borderColor: 'divider', p: { xs: 2, md: 3 } }}><Grid container spacing={2}><Grid size={{ xs: 12, md: 8 }}><Chip size="small" label={target.provenance === 'ai' ? 'AI suggested · user adopted' : 'User defined'} color={target.provenance === 'ai' ? 'secondary' : 'default'} /><Typography color="text.secondary" mt={1} whiteSpace="pre-line">{target.description}</Typography></Grid><Grid size={{ xs: 12, md: 4 }}>{target.latest_assessment ? <Typography variant="body2">Assessment confidence: {target.latest_assessment.overall_confidence}%</Typography> : <Alert severity="info">Not yet assessed</Alert>}</Grid></Grid>
      <Stack spacing={2} mt={3}>{target.criteria.map(criterion => { const selected = assets.filter(asset => criterion.asset_ids.includes(asset.id)); const assessment = assessments[criterion.id]; return <Card variant="outlined" key={criterion.id}><CardContent><Grid container spacing={2}><Grid size={{ xs: 12, md: 4 }}><Typography fontWeight={800}>{criterion.title}</Typography><Typography variant="body2" color="text.secondary">Weight {criterion.weight} · {criterion.description}</Typography></Grid><Grid size={{ xs: 12, md: 8 }}><Autocomplete multiple options={assets} value={selected} getOptionLabel={option => option.title} isOptionEqualToValue={(option, value) => option.id === value.id} onChange={(_, value) => void mapAssets(criterion.id, value)} renderInput={params => <TextField {...params} label="Mapped career assets" helperText={`${criterion.evidence_ids.length} evidence items linked`} />} /></Grid>{assessment && <><Grid size={{ xs: 12, md: 2 }}><TextField type="number" fullWidth label="Coverage %" value={assessment.coverage} slotProps={{ htmlInput: { min: 0, max: 100 } }} onChange={e => setAssessments(current => ({ ...current, [criterion.id]: { ...assessment, coverage: Number(e.target.value) } }))} /></Grid><Grid size={{ xs: 12, md: 2 }}><TextField type="number" fullWidth label="Confidence %" value={assessment.confidence} slotProps={{ htmlInput: { min: 0, max: 100 } }} onChange={e => setAssessments(current => ({ ...current, [criterion.id]: { ...assessment, confidence: Number(e.target.value) } }))} /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth label="Assessment explanation" value={assessment.explanation} onChange={e => setAssessments(current => ({ ...current, [criterion.id]: { ...assessment, explanation: e.target.value } }))} /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth label="Recommended action" value={assessment.recommended_action} onChange={e => setAssessments(current => ({ ...current, [criterion.id]: { ...assessment, recommended_action: e.target.value } }))} /></Grid></>}</Grid></CardContent></Card>})}</Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} mt={2}><Button variant="contained" disabled={busy || target.criteria.length === 0} onClick={() => void autoMap(target)}>Map existing evidence with AI</Button><Button variant="outlined" disabled={busy || target.criteria.length === 0} onClick={() => void assess(target)}>Save manual assessment</Button></Stack>
      {target.latest_assessment && <Grid container spacing={2} mt={1}><Grid size={{ xs: 12, md: 4 }}><Alert severity="success"><strong>Strengths:</strong> {target.latest_assessment.strengths.join(', ') || 'None above 70% yet'}</Alert></Grid><Grid size={{ xs: 12, md: 4 }}><Alert severity="warning"><strong>Gaps:</strong> {target.latest_assessment.gaps.join(', ') || 'No criteria below 50%'}</Alert></Grid><Grid size={{ xs: 12, md: 4 }}><Alert severity="info"><strong>Actions:</strong> {target.latest_assessment.recommendations.join(' · ') || 'No actions recorded'}</Alert></Grid></Grid>}
    </AccordionDetails></Accordion>)}</Stack>}{targets?.length === 0 && <Alert severity="info">Create a target or request AI suggestions to begin readiness planning.</Alert>}
    <TargetEditor open={editor} suggestion={adopting} onClose={() => setEditor(false)} onSaved={() => { setFeedback('Target adopted.'); void load() }} /><Feedback message={feedback} onClose={() => setFeedback(null)} /></>
}
