"""add career intelligence foundation

Revision ID: f3396633e04e
Revises: 20260721_0001
Create Date: 2026-07-21 11:44:42.024819
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "f3396633e04e"
down_revision: str | None = "20260721_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "career_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("current_title", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column(
            "current_organisation", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False
        ),
        sa.Column("career_mission", sa.Text(), nullable=False),
        sa.Column("career_narrative", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "original_filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column(
            "ai_handling_policy", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("extraction_status", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("extraction_error", sa.Text(), nullable=False),
        sa.Column("source_kind", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_index(op.f("ix_documents_sha256"), "documents", ["sha256"], unique=False)
    op.create_table(
        "organisations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column(
            "organisation_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("provenance", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_organisations_name"), "organisations", ["name"], unique=False)
    op.create_table(
        "strategic_goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("horizon", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("provenance", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategic_goals_horizon"), "strategic_goals", ["horizon"], unique=False
    )
    op.create_index(op.f("ix_strategic_goals_status"), "strategic_goals", ["status"], unique=False)
    op.create_table(
        "themes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("provenance", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_themes_name"), "themes", ["name"], unique=False)
    op.create_table(
        "career_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("subcategory", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("date_precision", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("impact_summary", sa.Text(), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("tags_json", sa.Text(), nullable=False),
        sa.Column("keywords_json", sa.Text(), nullable=False),
        sa.Column("source_kind", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_career_assets_category"), "career_assets", ["category"], unique=False)
    op.create_index(
        op.f("ix_career_assets_start_date"), "career_assets", ["start_date"], unique=False
    )
    op.create_index(op.f("ix_career_assets_status"), "career_assets", ["status"], unique=False)
    op.create_index(op.f("ix_career_assets_title"), "career_assets", ["title"], unique=False)
    op.create_table(
        "people",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "relationship_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "public_profile_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("provenance", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_name"), "people", ["name"], unique=False)
    op.create_table(
        "asset_theme_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("theme_id", sa.Uuid(), nullable=False),
        sa.Column("provenance", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["career_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["theme_id"], ["themes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "theme_id"),
    )
    op.create_index(
        op.f("ix_asset_theme_links_asset_id"), "asset_theme_links", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_asset_theme_links_theme_id"), "asset_theme_links", ["theme_id"], unique=False
    )
    op.create_table(
        "evidence_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("source_kind", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["career_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_items_asset_id"), "evidence_items", ["asset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_items_asset_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_asset_theme_links_theme_id"), table_name="asset_theme_links")
    op.drop_index(op.f("ix_asset_theme_links_asset_id"), table_name="asset_theme_links")
    op.drop_table("asset_theme_links")
    op.drop_index(op.f("ix_people_name"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_career_assets_title"), table_name="career_assets")
    op.drop_index(op.f("ix_career_assets_status"), table_name="career_assets")
    op.drop_index(op.f("ix_career_assets_start_date"), table_name="career_assets")
    op.drop_index(op.f("ix_career_assets_category"), table_name="career_assets")
    op.drop_table("career_assets")
    op.drop_index(op.f("ix_themes_name"), table_name="themes")
    op.drop_table("themes")
    op.drop_index(op.f("ix_strategic_goals_status"), table_name="strategic_goals")
    op.drop_index(op.f("ix_strategic_goals_horizon"), table_name="strategic_goals")
    op.drop_table("strategic_goals")
    op.drop_index(op.f("ix_organisations_name"), table_name="organisations")
    op.drop_table("organisations")
    op.drop_index(op.f("ix_documents_sha256"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("career_profiles")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
